### ISSUE TITLE
Mudar Formato de Apresentação - FRONTEND

### ISSUE THREAD

**Issue by PhMoraiis** [FGA0138-MDS-Ajax/2023-2-SIRIUS#43]
## **Problema**
Mudar o formato de apresentação dos dados em JSON para uma tabela, utilizando apenas as colunas de 'inGameName' e 'discordID'.

## **Solução**
Criar uma tabela, e mapear os campos para receber os dados.

**Branch**: `develop`

## **Principais Tasks**
- [x] Criar Tabela
- [x] Estilizar Tabela
- [x] Mapear Campos

## **Links**
Colocar links de protótipo, de campos ou documentos necessários para que o desenvolvedor possa encontrar de forma mais ágil.

## **Dificuldades**
Fale sobre alguma dificuldade que está encontrando ao processo de finalização da issue.

**Comment by fabioaletorres** [comment]
Alterado

**Comment by fabioaletorres** [comment]
finalizado
